"""Tabelas Vitima, Ofesor e Denuncia.

Revision ID: 3f934cb358f4
Revises: ecf51ff395d2
Create Date: 2025-11-25 22:53:30.035739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f934cb358f4'
down_revision: Union[str, Sequence[str], None] = 'ecf51ff395d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
