"""ADD COLUMNS & CREATE TABLE: criando uma tabela para anexos de arquivos para denuncias e FK na tabela de denuncias.

Revision ID: 3fa8a06fd089
Revises: 43265b9d1922
Create Date: 2026-05-28 10:36:55.137789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa8a06fd089'
down_revision: Union[str, Sequence[str], None] = '43265b9d1922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denuncias_anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_denuncia', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_denuncia'], ['denuncias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('denuncias_anexos')
    # ### end Alembic commands ###
