"""ADD COLUMNS & CREATE TABLE: criando uma tabela para anexos de arquivos para denuncias e FK na tabela de denuncias.

Revision ID: 43265b9d1922
Revises: 9fcde04f8913
Create Date: 2026-05-28 10:35:16.991750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43265b9d1922'
down_revision: Union[str, Sequence[str], None] = '9fcde04f8913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
