"""Add os relacionamentos das denuncias com relação a vitimas e ofesors.

Revision ID: 4ae9f83508a3
Revises: 8ee84752874f
Create Date: 2025-11-26 09:13:09.962647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae9f83508a3'
down_revision: Union[str, Sequence[str], None] = '8ee84752874f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('denuncias', sa.Column('vitima_id', sa.Integer(), nullable=False))
    op.add_column('denuncias', sa.Column('ofesor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'denuncias', 'ofesors', ['ofesor_id'], ['id'])
    op.create_foreign_key(None, 'denuncias', 'vitimas', ['vitima_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'denuncias', type_='foreignkey')
    op.drop_constraint(None, 'denuncias', type_='foreignkey')
    op.drop_column('denuncias', 'ofesor_id')
    op.drop_column('denuncias', 'vitima_id')
    # ### end Alembic commands ###
