"""Add coluna de nomes de testemunhas na tabela denuncias.

Revision ID: 818eba5fc4b6
Revises: 8a6c3a699dd6
Create Date: 2025-11-28 14:41:50.682415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818eba5fc4b6'
down_revision: Union[str, Sequence[str], None] = '8a6c3a699dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('denuncias', sa.Column('nomes_testemunhas', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('denuncias', 'nomes_testemunhas')
    # ### end Alembic commands ###
