"""Remoção da coluna de matricula da tabela de vitima.

Revision ID: 828a7f0eda49
Revises: 4ae9f83508a3
Create Date: 2025-11-26 15:12:15.579261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '828a7f0eda49'
down_revision: Union[str, Sequence[str], None] = '4ae9f83508a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('matricula'), table_name='vitimas')
    op.drop_column('vitimas', 'matricula')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vitimas', sa.Column('matricula', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('matricula'), 'vitimas', ['matricula'], unique=True)
    # ### end Alembic commands ###
