"""Remoção da coluna de matricula da tabela de vitima.

Revision ID: 8a6c3a699dd6
Revises: 828a7f0eda49
Create Date: 2025-11-26 15:14:28.454336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6c3a699dd6'
down_revision: Union[str, Sequence[str], None] = '828a7f0eda49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
