"""add columns, table denuncias.

Revision ID: 9fcde04f8913
Revises: e92b30bf9ba2
Create Date: 2026-02-02 15:48:19.768510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fcde04f8913'
down_revision: Union[str, Sequence[str], None] = 'e92b30bf9ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('denuncias', sa.Column('status', sa.String(length=25), nullable=True))
    op.add_column('denuncias', sa.Column('severidade', sa.String(length=25), nullable=True))
    op.add_column('denuncias', sa.Column('evidencias', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('denuncias', 'evidencias')
    op.drop_column('denuncias', 'severidade')
    op.drop_column('denuncias', 'status')
    # ### end Alembic commands ###
