"""ADD COLUMNS: linha de depoimentos.

Revision ID: aae95a3bc222
Revises: 3fa8a06fd089
Create Date: 2026-06-02 10:33:48.366419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae95a3bc222'
down_revision: Union[str, Sequence[str], None] = '3fa8a06fd089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('denuncias', sa.Column('depoimento_vitima', sa.Text(), nullable=True))
    op.add_column('denuncias', sa.Column('depoimento_acusado', sa.Text(), nullable=True))
    op.add_column('denuncias', sa.Column('depoimento_testemunha', sa.Text(), nullable=True))
    op.add_column('denuncias', sa.Column('depoimento_admin', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('denuncias', 'depoimento_admin')
    op.drop_column('denuncias', 'depoimento_testemunha')
    op.drop_column('denuncias', 'depoimento_acusado')
    op.drop_column('denuncias', 'depoimento_vitima')
    # ### end Alembic commands ###
