"""Tabelas Vitima, Ofesor e Denuncia.

Revision ID: acfc967ce5f1
Revises: 3f934cb358f4
Create Date: 2025-11-25 22:54:41.315868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfc967ce5f1'
down_revision: Union[str, Sequence[str], None] = '3f934cb358f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
