"""alter a coluna de data_public para aceita dados none.

Revision ID: e92b30bf9ba2
Revises: 8b62ead9efc2
Create Date: 2026-01-15 14:11:37.367395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92b30bf9ba2'
down_revision: Union[str, Sequence[str], None] = '8b62ead9efc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('denuncias', 'data_public',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('denuncias', 'data_public',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
