"""Removendo coluna de genero na tabela de vitimas.

Revision ID: f3ed894f16c7
Revises: 818eba5fc4b6
Create Date: 2025-11-28 16:39:13.186900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3ed894f16c7'
down_revision: Union[str, Sequence[str], None] = '818eba5fc4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vitimas', 'genero')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vitimas', sa.Column('genero', mysql.VARCHAR(length=25), nullable=False))
    # ### end Alembic commands ###
